#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d                     www dots misc code pdf file key vid chat

bspc config border_width            2
bspc config window_gap              0
bspc config top_padding             26

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config focused_border_color    \#454963 
bspc config normal_border_color     \#15161e

bspc rule -a Arandr                 state=floating
bspc rule -a matlab                 state=floating
bspc rule -a Zathura                state=tiled

~/dotfiles/scripts/launch.sh
