#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d                     1 2 3 4 5 6 7 8 9

bspc config border_width            2
bspc config window_gap              0
bspc config top_padding             26

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config focused_border_color    \#ebcb8b
bspc config normal_border_color     \#434c5e

bspc rule -a Zathura state=tiled

~/dotfiles/scripts/launch.sh
