baseURL: https://www.carldelfin.com
languageCode: en-us
title: 
theme: hugo-theme-cactus
copyright: Carl Delfin
disqusShortname: example
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 4
markup:
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: no
    lineNumbersInTable: no
    noClasses: yes
    style: friendly
    tabWidth: 4
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: classic
  dateFormat: '2006-01-02'
  description: My name is Slim Shady.
  googleAnalyticsAsync: yes
  mainSection: posts
  mainSectionTitle: "Recent posts"
  postsOnHomePage: 10
  projectsUrl: https://github.com/gohugoio
  rss: no
  show_updated: yes
  showAllPostsArchive: no
  showAllPostsOnHomePage: no
  showProjectsList: no
  showReadTime: no
  social:
    - link: https://github.com/gohugoio
      name: github
    - link: test.com
      name: orcid
    - link: test.com
      name: scholar
  tagsOverview: no
